// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::ap_ST_fsm_state1 = "1";
const sc_lv<32> dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<15> dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::ap_const_lv15_53 = "1010011";
const sc_lv<15> dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::ap_const_lv15_7FD2 = "111111111010010";
const sc_lv<32> dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::ap_const_lv32_2 = "10";
const sc_lv<32> dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::ap_const_lv32_E = "1110";
const sc_lv<15> dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::ap_const_lv15_0 = "000000000000000";
const bool dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::ap_const_boolean_1 = true;

dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln703_fu_117_p2);
    sensitive << ( sext_ln708_11_cast_fu_94_p1 );
    sensitive << ( sext_ln708_8_cast_fu_113_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln703_fu_117_p2 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_mul_ln1118_fu_47_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mul_ln1118_fu_47_p00 );

    SC_METHOD(thread_mul_ln1118_fu_47_p00);
    sensitive << ( p_read1 );

    SC_METHOD(thread_mul_ln1118_fu_47_p2);
    sensitive << ( mul_ln1118_fu_47_p0 );

    SC_METHOD(thread_mul_ln708_fu_46_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mul_ln708_fu_46_p00 );

    SC_METHOD(thread_mul_ln708_fu_46_p00);
    sensitive << ( p_read );

    SC_METHOD(thread_mul_ln708_fu_46_p2);
    sensitive << ( mul_ln708_fu_46_p0 );

    SC_METHOD(thread_sext_ln708_11_cast_fu_94_p1);
    sensitive << ( tmp_fu_84_p4 );

    SC_METHOD(thread_sext_ln708_8_cast_fu_113_p1);
    sensitive << ( trunc_ln708_s_fu_103_p4 );

    SC_METHOD(thread_tmp_fu_84_p4);
    sensitive << ( mul_ln708_fu_46_p2 );

    SC_METHOD(thread_trunc_ln708_s_fu_103_p4);
    sensitive << ( mul_ln1118_fu_47_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "1";
    ap_return_preg = "000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_read, "(port)p_read");
    sc_trace(mVcdFile, p_read1, "(port)p_read1");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, mul_ln708_fu_46_p0, "mul_ln708_fu_46_p0");
    sc_trace(mVcdFile, mul_ln1118_fu_47_p0, "mul_ln1118_fu_47_p0");
    sc_trace(mVcdFile, mul_ln708_fu_46_p2, "mul_ln708_fu_46_p2");
    sc_trace(mVcdFile, tmp_fu_84_p4, "tmp_fu_84_p4");
    sc_trace(mVcdFile, mul_ln1118_fu_47_p2, "mul_ln1118_fu_47_p2");
    sc_trace(mVcdFile, trunc_ln708_s_fu_103_p4, "trunc_ln708_s_fu_103_p4");
    sc_trace(mVcdFile, sext_ln708_11_cast_fu_94_p1, "sext_ln708_11_cast_fu_94_p1");
    sc_trace(mVcdFile, sext_ln708_8_cast_fu_113_p1, "sext_ln708_8_cast_fu_113_p1");
    sc_trace(mVcdFile, add_ln703_fu_117_p2, "add_ln703_fu_117_p2");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, mul_ln1118_fu_47_p00, "mul_ln1118_fu_47_p00");
    sc_trace(mVcdFile, mul_ln708_fu_46_p00, "mul_ln708_fu_46_p00");
#endif

    }
}

dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::~dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv15_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_preg = add_ln703_fu_117_p2.read();
        }
    }
}

void dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::thread_add_ln703_fu_117_p2() {
    add_ln703_fu_117_p2 = (!sext_ln708_11_cast_fu_94_p1.read().is_01() || !sext_ln708_8_cast_fu_113_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(sext_ln708_11_cast_fu_94_p1.read()) + sc_bigint<15>(sext_ln708_8_cast_fu_113_p1.read()));
}

void dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return = add_ln703_fu_117_p2.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::thread_mul_ln1118_fu_47_p0() {
    mul_ln1118_fu_47_p0 =  (sc_lv<8>) (mul_ln1118_fu_47_p00.read());
}

void dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::thread_mul_ln1118_fu_47_p00() {
    mul_ln1118_fu_47_p00 = esl_zext<15,8>(p_read1.read());
}

void dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::thread_mul_ln1118_fu_47_p2() {
    mul_ln1118_fu_47_p2 = (!mul_ln1118_fu_47_p0.read().is_01() || !ap_const_lv15_7FD2.is_01())? sc_lv<15>(): sc_biguint<8>(mul_ln1118_fu_47_p0.read()) * sc_bigint<15>(ap_const_lv15_7FD2);
}

void dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::thread_mul_ln708_fu_46_p0() {
    mul_ln708_fu_46_p0 =  (sc_lv<8>) (mul_ln708_fu_46_p00.read());
}

void dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::thread_mul_ln708_fu_46_p00() {
    mul_ln708_fu_46_p00 = esl_zext<15,8>(p_read.read());
}

void dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::thread_mul_ln708_fu_46_p2() {
    mul_ln708_fu_46_p2 = (!mul_ln708_fu_46_p0.read().is_01() || !ap_const_lv15_53.is_01())? sc_lv<15>(): sc_biguint<8>(mul_ln708_fu_46_p0.read()) * sc_biguint<15>(ap_const_lv15_53);
}

void dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::thread_sext_ln708_11_cast_fu_94_p1() {
    sext_ln708_11_cast_fu_94_p1 = esl_zext<15,13>(tmp_fu_84_p4.read());
}

void dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::thread_sext_ln708_8_cast_fu_113_p1() {
    sext_ln708_8_cast_fu_113_p1 = esl_sext<15,13>(trunc_ln708_s_fu_103_p4.read());
}

void dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::thread_tmp_fu_84_p4() {
    tmp_fu_84_p4 = mul_ln708_fu_46_p2.read().range(14, 2);
}

void dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::thread_trunc_ln708_s_fu_103_p4() {
    trunc_ln708_s_fu_103_p4 = mul_ln1118_fu_47_p2.read().range(14, 2);
}

void dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config12_0_0::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

