// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::ap_ST_fsm_pp0_stage0 = "1";
const sc_lv<32> global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::ap_const_boolean_1 = true;
const bool global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::ap_const_boolean_0 = false;
const sc_lv<2> global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::ap_const_lv2_0 = "00";
const sc_lv<10> global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::ap_const_lv10_0 = "0000000000";

global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818 = new pool_op_ap_ufixed_8_0_4_0_0_10_1_s("grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818");
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818->ap_clk(ap_clk);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818->ap_rst(ap_rst);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818->x_0_V_read(data_0_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818->x_1_V_read(data_10_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818->x_2_V_read(data_20_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818->x_3_V_read(data_30_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818->x_4_V_read(data_40_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818->x_5_V_read(data_50_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818->x_6_V_read(data_60_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818->x_7_V_read(data_70_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818->x_8_V_read(data_80_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818->x_9_V_read(data_90_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818->ap_return(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818_ap_return);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818->ap_ce(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818_ap_ce);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842 = new pool_op_ap_ufixed_8_0_4_0_0_10_1_s("grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842");
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842->ap_clk(ap_clk);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842->ap_rst(ap_rst);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842->x_0_V_read(data_1_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842->x_1_V_read(data_11_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842->x_2_V_read(data_21_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842->x_3_V_read(data_31_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842->x_4_V_read(data_41_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842->x_5_V_read(data_51_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842->x_6_V_read(data_61_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842->x_7_V_read(data_71_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842->x_8_V_read(data_81_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842->x_9_V_read(data_91_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842->ap_return(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842_ap_return);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842->ap_ce(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842_ap_ce);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866 = new pool_op_ap_ufixed_8_0_4_0_0_10_1_s("grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866");
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866->ap_clk(ap_clk);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866->ap_rst(ap_rst);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866->x_0_V_read(data_2_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866->x_1_V_read(data_12_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866->x_2_V_read(data_22_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866->x_3_V_read(data_32_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866->x_4_V_read(data_42_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866->x_5_V_read(data_52_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866->x_6_V_read(data_62_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866->x_7_V_read(data_72_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866->x_8_V_read(data_82_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866->x_9_V_read(data_92_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866->ap_return(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866_ap_return);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866->ap_ce(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866_ap_ce);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890 = new pool_op_ap_ufixed_8_0_4_0_0_10_1_s("grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890");
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890->ap_clk(ap_clk);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890->ap_rst(ap_rst);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890->x_0_V_read(data_3_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890->x_1_V_read(data_13_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890->x_2_V_read(data_23_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890->x_3_V_read(data_33_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890->x_4_V_read(data_43_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890->x_5_V_read(data_53_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890->x_6_V_read(data_63_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890->x_7_V_read(data_73_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890->x_8_V_read(data_83_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890->x_9_V_read(data_93_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890->ap_return(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890_ap_return);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890->ap_ce(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890_ap_ce);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914 = new pool_op_ap_ufixed_8_0_4_0_0_10_1_s("grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914");
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914->ap_clk(ap_clk);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914->ap_rst(ap_rst);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914->x_0_V_read(data_4_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914->x_1_V_read(data_14_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914->x_2_V_read(data_24_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914->x_3_V_read(data_34_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914->x_4_V_read(data_44_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914->x_5_V_read(data_54_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914->x_6_V_read(data_64_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914->x_7_V_read(data_74_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914->x_8_V_read(data_84_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914->x_9_V_read(data_94_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914->ap_return(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914_ap_return);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914->ap_ce(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914_ap_ce);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938 = new pool_op_ap_ufixed_8_0_4_0_0_10_1_s("grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938");
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938->ap_clk(ap_clk);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938->ap_rst(ap_rst);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938->x_0_V_read(data_5_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938->x_1_V_read(data_15_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938->x_2_V_read(data_25_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938->x_3_V_read(data_35_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938->x_4_V_read(data_45_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938->x_5_V_read(data_55_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938->x_6_V_read(data_65_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938->x_7_V_read(data_75_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938->x_8_V_read(data_85_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938->x_9_V_read(data_95_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938->ap_return(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938_ap_return);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938->ap_ce(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938_ap_ce);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962 = new pool_op_ap_ufixed_8_0_4_0_0_10_1_s("grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962");
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962->ap_clk(ap_clk);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962->ap_rst(ap_rst);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962->x_0_V_read(data_6_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962->x_1_V_read(data_16_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962->x_2_V_read(data_26_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962->x_3_V_read(data_36_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962->x_4_V_read(data_46_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962->x_5_V_read(data_56_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962->x_6_V_read(data_66_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962->x_7_V_read(data_76_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962->x_8_V_read(data_86_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962->x_9_V_read(data_96_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962->ap_return(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962_ap_return);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962->ap_ce(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962_ap_ce);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986 = new pool_op_ap_ufixed_8_0_4_0_0_10_1_s("grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986");
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986->ap_clk(ap_clk);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986->ap_rst(ap_rst);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986->x_0_V_read(data_7_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986->x_1_V_read(data_17_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986->x_2_V_read(data_27_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986->x_3_V_read(data_37_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986->x_4_V_read(data_47_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986->x_5_V_read(data_57_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986->x_6_V_read(data_67_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986->x_7_V_read(data_77_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986->x_8_V_read(data_87_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986->x_9_V_read(data_97_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986->ap_return(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986_ap_return);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986->ap_ce(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986_ap_ce);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010 = new pool_op_ap_ufixed_8_0_4_0_0_10_1_s("grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010");
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010->ap_clk(ap_clk);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010->ap_rst(ap_rst);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010->x_0_V_read(data_8_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010->x_1_V_read(data_18_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010->x_2_V_read(data_28_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010->x_3_V_read(data_38_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010->x_4_V_read(data_48_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010->x_5_V_read(data_58_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010->x_6_V_read(data_68_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010->x_7_V_read(data_78_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010->x_8_V_read(data_88_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010->x_9_V_read(data_98_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010->ap_return(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010_ap_return);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010->ap_ce(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010_ap_ce);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034 = new pool_op_ap_ufixed_8_0_4_0_0_10_1_s("grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034");
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034->ap_clk(ap_clk);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034->ap_rst(ap_rst);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034->x_0_V_read(data_9_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034->x_1_V_read(data_19_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034->x_2_V_read(data_29_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034->x_3_V_read(data_39_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034->x_4_V_read(data_49_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034->x_5_V_read(data_59_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034->x_6_V_read(data_69_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034->x_7_V_read(data_79_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034->x_8_V_read(data_89_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034->x_9_V_read(data_99_V_read);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034->ap_return(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034_ap_return);
    grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034->ap_ce(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034_ap_ce);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001_ignoreCallOp105);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001_ignoreCallOp106);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001_ignoreCallOp107);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001_ignoreCallOp108);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001_ignoreCallOp109);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001_ignoreCallOp110);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001_ignoreCallOp111);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001_ignoreCallOp112);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001_ignoreCallOp113);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001_ignoreCallOp114);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0_ignore_call101);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0_ignore_call102);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0_ignore_call103);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0_ignore_call106);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0_ignore_call109);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0_ignore_call112);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0_ignore_call113);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0_ignore_call114);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0_ignore_call115);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0_ignore_call116);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1_ignore_call101);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1_ignore_call102);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1_ignore_call103);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1_ignore_call106);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1_ignore_call109);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1_ignore_call112);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1_ignore_call113);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1_ignore_call114);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1_ignore_call115);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1_ignore_call116);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2_ignore_call101);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2_ignore_call102);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2_ignore_call103);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2_ignore_call106);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2_ignore_call109);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2_ignore_call112);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2_ignore_call113);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2_ignore_call114);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2_ignore_call115);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2_ignore_call116);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3_ignore_call101);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3_ignore_call102);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3_ignore_call103);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3_ignore_call106);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3_ignore_call109);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3_ignore_call112);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3_ignore_call113);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3_ignore_call114);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3_ignore_call115);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3_ignore_call116);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_ap_idle_pp0_0to2);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to2 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( zext_ln728_fu_1066_p1 );
    sensitive << ( ap_return_0_preg );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( zext_ln728_1_fu_1078_p1 );
    sensitive << ( ap_return_1_preg );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( zext_ln728_2_fu_1090_p1 );
    sensitive << ( ap_return_2_preg );

    SC_METHOD(thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010_ap_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001_ignoreCallOp113 );

    SC_METHOD(thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034_ap_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001_ignoreCallOp114 );

    SC_METHOD(thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818_ap_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001_ignoreCallOp105 );

    SC_METHOD(thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842_ap_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001_ignoreCallOp106 );

    SC_METHOD(thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866_ap_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001_ignoreCallOp107 );

    SC_METHOD(thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890_ap_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001_ignoreCallOp108 );

    SC_METHOD(thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914_ap_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001_ignoreCallOp109 );

    SC_METHOD(thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938_ap_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001_ignoreCallOp110 );

    SC_METHOD(thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962_ap_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001_ignoreCallOp111 );

    SC_METHOD(thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986_ap_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001_ignoreCallOp112 );

    SC_METHOD(thread_res_2_V_write_assign_fu_1058_p3);
    sensitive << ( grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866_ap_return );

    SC_METHOD(thread_res_3_V_write_assign_fu_1070_p3);
    sensitive << ( grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890_ap_return );

    SC_METHOD(thread_res_4_V_write_assign_fu_1082_p3);
    sensitive << ( grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914_ap_return );

    SC_METHOD(thread_zext_ln728_1_fu_1078_p1);
    sensitive << ( res_3_V_write_assign_fu_1070_p3 );

    SC_METHOD(thread_zext_ln728_2_fu_1090_p1);
    sensitive << ( res_4_V_write_assign_fu_1082_p3 );

    SC_METHOD(thread_zext_ln728_fu_1066_p1);
    sensitive << ( res_2_V_write_assign_fu_1058_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_return_0_preg = "0000000000";
    ap_return_1_preg = "0000000000";
    ap_return_2_preg = "0000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_5_V_read, "(port)data_5_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, data_7_V_read, "(port)data_7_V_read");
    sc_trace(mVcdFile, data_8_V_read, "(port)data_8_V_read");
    sc_trace(mVcdFile, data_9_V_read, "(port)data_9_V_read");
    sc_trace(mVcdFile, data_10_V_read, "(port)data_10_V_read");
    sc_trace(mVcdFile, data_11_V_read, "(port)data_11_V_read");
    sc_trace(mVcdFile, data_12_V_read, "(port)data_12_V_read");
    sc_trace(mVcdFile, data_13_V_read, "(port)data_13_V_read");
    sc_trace(mVcdFile, data_14_V_read, "(port)data_14_V_read");
    sc_trace(mVcdFile, data_15_V_read, "(port)data_15_V_read");
    sc_trace(mVcdFile, data_16_V_read, "(port)data_16_V_read");
    sc_trace(mVcdFile, data_17_V_read, "(port)data_17_V_read");
    sc_trace(mVcdFile, data_18_V_read, "(port)data_18_V_read");
    sc_trace(mVcdFile, data_19_V_read, "(port)data_19_V_read");
    sc_trace(mVcdFile, data_20_V_read, "(port)data_20_V_read");
    sc_trace(mVcdFile, data_21_V_read, "(port)data_21_V_read");
    sc_trace(mVcdFile, data_22_V_read, "(port)data_22_V_read");
    sc_trace(mVcdFile, data_23_V_read, "(port)data_23_V_read");
    sc_trace(mVcdFile, data_24_V_read, "(port)data_24_V_read");
    sc_trace(mVcdFile, data_25_V_read, "(port)data_25_V_read");
    sc_trace(mVcdFile, data_26_V_read, "(port)data_26_V_read");
    sc_trace(mVcdFile, data_27_V_read, "(port)data_27_V_read");
    sc_trace(mVcdFile, data_28_V_read, "(port)data_28_V_read");
    sc_trace(mVcdFile, data_29_V_read, "(port)data_29_V_read");
    sc_trace(mVcdFile, data_30_V_read, "(port)data_30_V_read");
    sc_trace(mVcdFile, data_31_V_read, "(port)data_31_V_read");
    sc_trace(mVcdFile, data_32_V_read, "(port)data_32_V_read");
    sc_trace(mVcdFile, data_33_V_read, "(port)data_33_V_read");
    sc_trace(mVcdFile, data_34_V_read, "(port)data_34_V_read");
    sc_trace(mVcdFile, data_35_V_read, "(port)data_35_V_read");
    sc_trace(mVcdFile, data_36_V_read, "(port)data_36_V_read");
    sc_trace(mVcdFile, data_37_V_read, "(port)data_37_V_read");
    sc_trace(mVcdFile, data_38_V_read, "(port)data_38_V_read");
    sc_trace(mVcdFile, data_39_V_read, "(port)data_39_V_read");
    sc_trace(mVcdFile, data_40_V_read, "(port)data_40_V_read");
    sc_trace(mVcdFile, data_41_V_read, "(port)data_41_V_read");
    sc_trace(mVcdFile, data_42_V_read, "(port)data_42_V_read");
    sc_trace(mVcdFile, data_43_V_read, "(port)data_43_V_read");
    sc_trace(mVcdFile, data_44_V_read, "(port)data_44_V_read");
    sc_trace(mVcdFile, data_45_V_read, "(port)data_45_V_read");
    sc_trace(mVcdFile, data_46_V_read, "(port)data_46_V_read");
    sc_trace(mVcdFile, data_47_V_read, "(port)data_47_V_read");
    sc_trace(mVcdFile, data_48_V_read, "(port)data_48_V_read");
    sc_trace(mVcdFile, data_49_V_read, "(port)data_49_V_read");
    sc_trace(mVcdFile, data_50_V_read, "(port)data_50_V_read");
    sc_trace(mVcdFile, data_51_V_read, "(port)data_51_V_read");
    sc_trace(mVcdFile, data_52_V_read, "(port)data_52_V_read");
    sc_trace(mVcdFile, data_53_V_read, "(port)data_53_V_read");
    sc_trace(mVcdFile, data_54_V_read, "(port)data_54_V_read");
    sc_trace(mVcdFile, data_55_V_read, "(port)data_55_V_read");
    sc_trace(mVcdFile, data_56_V_read, "(port)data_56_V_read");
    sc_trace(mVcdFile, data_57_V_read, "(port)data_57_V_read");
    sc_trace(mVcdFile, data_58_V_read, "(port)data_58_V_read");
    sc_trace(mVcdFile, data_59_V_read, "(port)data_59_V_read");
    sc_trace(mVcdFile, data_60_V_read, "(port)data_60_V_read");
    sc_trace(mVcdFile, data_61_V_read, "(port)data_61_V_read");
    sc_trace(mVcdFile, data_62_V_read, "(port)data_62_V_read");
    sc_trace(mVcdFile, data_63_V_read, "(port)data_63_V_read");
    sc_trace(mVcdFile, data_64_V_read, "(port)data_64_V_read");
    sc_trace(mVcdFile, data_65_V_read, "(port)data_65_V_read");
    sc_trace(mVcdFile, data_66_V_read, "(port)data_66_V_read");
    sc_trace(mVcdFile, data_67_V_read, "(port)data_67_V_read");
    sc_trace(mVcdFile, data_68_V_read, "(port)data_68_V_read");
    sc_trace(mVcdFile, data_69_V_read, "(port)data_69_V_read");
    sc_trace(mVcdFile, data_70_V_read, "(port)data_70_V_read");
    sc_trace(mVcdFile, data_71_V_read, "(port)data_71_V_read");
    sc_trace(mVcdFile, data_72_V_read, "(port)data_72_V_read");
    sc_trace(mVcdFile, data_73_V_read, "(port)data_73_V_read");
    sc_trace(mVcdFile, data_74_V_read, "(port)data_74_V_read");
    sc_trace(mVcdFile, data_75_V_read, "(port)data_75_V_read");
    sc_trace(mVcdFile, data_76_V_read, "(port)data_76_V_read");
    sc_trace(mVcdFile, data_77_V_read, "(port)data_77_V_read");
    sc_trace(mVcdFile, data_78_V_read, "(port)data_78_V_read");
    sc_trace(mVcdFile, data_79_V_read, "(port)data_79_V_read");
    sc_trace(mVcdFile, data_80_V_read, "(port)data_80_V_read");
    sc_trace(mVcdFile, data_81_V_read, "(port)data_81_V_read");
    sc_trace(mVcdFile, data_82_V_read, "(port)data_82_V_read");
    sc_trace(mVcdFile, data_83_V_read, "(port)data_83_V_read");
    sc_trace(mVcdFile, data_84_V_read, "(port)data_84_V_read");
    sc_trace(mVcdFile, data_85_V_read, "(port)data_85_V_read");
    sc_trace(mVcdFile, data_86_V_read, "(port)data_86_V_read");
    sc_trace(mVcdFile, data_87_V_read, "(port)data_87_V_read");
    sc_trace(mVcdFile, data_88_V_read, "(port)data_88_V_read");
    sc_trace(mVcdFile, data_89_V_read, "(port)data_89_V_read");
    sc_trace(mVcdFile, data_90_V_read, "(port)data_90_V_read");
    sc_trace(mVcdFile, data_91_V_read, "(port)data_91_V_read");
    sc_trace(mVcdFile, data_92_V_read, "(port)data_92_V_read");
    sc_trace(mVcdFile, data_93_V_read, "(port)data_93_V_read");
    sc_trace(mVcdFile, data_94_V_read, "(port)data_94_V_read");
    sc_trace(mVcdFile, data_95_V_read, "(port)data_95_V_read");
    sc_trace(mVcdFile, data_96_V_read, "(port)data_96_V_read");
    sc_trace(mVcdFile, data_97_V_read, "(port)data_97_V_read");
    sc_trace(mVcdFile, data_98_V_read, "(port)data_98_V_read");
    sc_trace(mVcdFile, data_99_V_read, "(port)data_99_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818_ap_return, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818_ap_return");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818_ap_ce, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818_ap_ce");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0_ignore_call101, "ap_block_state1_pp0_stage0_iter0_ignore_call101");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1_ignore_call101, "ap_block_state2_pp0_stage0_iter1_ignore_call101");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2_ignore_call101, "ap_block_state3_pp0_stage0_iter2_ignore_call101");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3_ignore_call101, "ap_block_state4_pp0_stage0_iter3_ignore_call101");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001_ignoreCallOp105, "ap_block_pp0_stage0_11001_ignoreCallOp105");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842_ap_return, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842_ap_return");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842_ap_ce, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842_ap_ce");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0_ignore_call102, "ap_block_state1_pp0_stage0_iter0_ignore_call102");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1_ignore_call102, "ap_block_state2_pp0_stage0_iter1_ignore_call102");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2_ignore_call102, "ap_block_state3_pp0_stage0_iter2_ignore_call102");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3_ignore_call102, "ap_block_state4_pp0_stage0_iter3_ignore_call102");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001_ignoreCallOp106, "ap_block_pp0_stage0_11001_ignoreCallOp106");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866_ap_return, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866_ap_return");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866_ap_ce, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866_ap_ce");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0_ignore_call103, "ap_block_state1_pp0_stage0_iter0_ignore_call103");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1_ignore_call103, "ap_block_state2_pp0_stage0_iter1_ignore_call103");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2_ignore_call103, "ap_block_state3_pp0_stage0_iter2_ignore_call103");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3_ignore_call103, "ap_block_state4_pp0_stage0_iter3_ignore_call103");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001_ignoreCallOp107, "ap_block_pp0_stage0_11001_ignoreCallOp107");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890_ap_return, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890_ap_return");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890_ap_ce, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890_ap_ce");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0_ignore_call106, "ap_block_state1_pp0_stage0_iter0_ignore_call106");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1_ignore_call106, "ap_block_state2_pp0_stage0_iter1_ignore_call106");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2_ignore_call106, "ap_block_state3_pp0_stage0_iter2_ignore_call106");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3_ignore_call106, "ap_block_state4_pp0_stage0_iter3_ignore_call106");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001_ignoreCallOp108, "ap_block_pp0_stage0_11001_ignoreCallOp108");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914_ap_return, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914_ap_return");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914_ap_ce, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914_ap_ce");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0_ignore_call109, "ap_block_state1_pp0_stage0_iter0_ignore_call109");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1_ignore_call109, "ap_block_state2_pp0_stage0_iter1_ignore_call109");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2_ignore_call109, "ap_block_state3_pp0_stage0_iter2_ignore_call109");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3_ignore_call109, "ap_block_state4_pp0_stage0_iter3_ignore_call109");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001_ignoreCallOp109, "ap_block_pp0_stage0_11001_ignoreCallOp109");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938_ap_return, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938_ap_return");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938_ap_ce, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938_ap_ce");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0_ignore_call112, "ap_block_state1_pp0_stage0_iter0_ignore_call112");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1_ignore_call112, "ap_block_state2_pp0_stage0_iter1_ignore_call112");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2_ignore_call112, "ap_block_state3_pp0_stage0_iter2_ignore_call112");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3_ignore_call112, "ap_block_state4_pp0_stage0_iter3_ignore_call112");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001_ignoreCallOp110, "ap_block_pp0_stage0_11001_ignoreCallOp110");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962_ap_return, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962_ap_return");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962_ap_ce, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962_ap_ce");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0_ignore_call113, "ap_block_state1_pp0_stage0_iter0_ignore_call113");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1_ignore_call113, "ap_block_state2_pp0_stage0_iter1_ignore_call113");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2_ignore_call113, "ap_block_state3_pp0_stage0_iter2_ignore_call113");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3_ignore_call113, "ap_block_state4_pp0_stage0_iter3_ignore_call113");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001_ignoreCallOp111, "ap_block_pp0_stage0_11001_ignoreCallOp111");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986_ap_return, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986_ap_return");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986_ap_ce, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986_ap_ce");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0_ignore_call114, "ap_block_state1_pp0_stage0_iter0_ignore_call114");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1_ignore_call114, "ap_block_state2_pp0_stage0_iter1_ignore_call114");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2_ignore_call114, "ap_block_state3_pp0_stage0_iter2_ignore_call114");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3_ignore_call114, "ap_block_state4_pp0_stage0_iter3_ignore_call114");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001_ignoreCallOp112, "ap_block_pp0_stage0_11001_ignoreCallOp112");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010_ap_return, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010_ap_return");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010_ap_ce, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010_ap_ce");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0_ignore_call115, "ap_block_state1_pp0_stage0_iter0_ignore_call115");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1_ignore_call115, "ap_block_state2_pp0_stage0_iter1_ignore_call115");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2_ignore_call115, "ap_block_state3_pp0_stage0_iter2_ignore_call115");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3_ignore_call115, "ap_block_state4_pp0_stage0_iter3_ignore_call115");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001_ignoreCallOp113, "ap_block_pp0_stage0_11001_ignoreCallOp113");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034_ap_return, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034_ap_return");
    sc_trace(mVcdFile, grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034_ap_ce, "grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034_ap_ce");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0_ignore_call116, "ap_block_state1_pp0_stage0_iter0_ignore_call116");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1_ignore_call116, "ap_block_state2_pp0_stage0_iter1_ignore_call116");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2_ignore_call116, "ap_block_state3_pp0_stage0_iter2_ignore_call116");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3_ignore_call116, "ap_block_state4_pp0_stage0_iter3_ignore_call116");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001_ignoreCallOp114, "ap_block_pp0_stage0_11001_ignoreCallOp114");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, res_2_V_write_assign_fu_1058_p3, "res_2_V_write_assign_fu_1058_p3");
    sc_trace(mVcdFile, res_3_V_write_assign_fu_1070_p3, "res_3_V_write_assign_fu_1070_p3");
    sc_trace(mVcdFile, res_4_V_write_assign_fu_1082_p3, "res_4_V_write_assign_fu_1082_p3");
    sc_trace(mVcdFile, zext_ln728_fu_1066_p1, "zext_ln728_fu_1066_p1");
    sc_trace(mVcdFile, zext_ln728_1_fu_1078_p1, "zext_ln728_1_fu_1078_p1");
    sc_trace(mVcdFile, zext_ln728_2_fu_1090_p1, "zext_ln728_2_fu_1090_p1");
    sc_trace(mVcdFile, ap_return_0_preg, "ap_return_0_preg");
    sc_trace(mVcdFile, ap_return_1_preg, "ap_return_1_preg");
    sc_trace(mVcdFile, ap_return_2_preg, "ap_return_2_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to2, "ap_idle_pp0_0to2");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::~global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818;
    delete grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842;
    delete grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866;
    delete grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890;
    delete grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914;
    delete grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938;
    delete grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962;
    delete grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986;
    delete grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010;
    delete grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034;
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_0_preg = ap_const_lv10_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
            ap_return_0_preg = zext_ln728_fu_1066_p1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_1_preg = ap_const_lv10_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
            ap_return_1_preg = zext_ln728_1_fu_1078_p1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_2_preg = ap_const_lv10_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
            ap_return_2_preg = zext_ln728_2_fu_1090_p1.read();
        }
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_pp0_stage0_11001_ignoreCallOp105() {
    ap_block_pp0_stage0_11001_ignoreCallOp105 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_pp0_stage0_11001_ignoreCallOp106() {
    ap_block_pp0_stage0_11001_ignoreCallOp106 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_pp0_stage0_11001_ignoreCallOp107() {
    ap_block_pp0_stage0_11001_ignoreCallOp107 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_pp0_stage0_11001_ignoreCallOp108() {
    ap_block_pp0_stage0_11001_ignoreCallOp108 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_pp0_stage0_11001_ignoreCallOp109() {
    ap_block_pp0_stage0_11001_ignoreCallOp109 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_pp0_stage0_11001_ignoreCallOp110() {
    ap_block_pp0_stage0_11001_ignoreCallOp110 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_pp0_stage0_11001_ignoreCallOp111() {
    ap_block_pp0_stage0_11001_ignoreCallOp111 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_pp0_stage0_11001_ignoreCallOp112() {
    ap_block_pp0_stage0_11001_ignoreCallOp112 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_pp0_stage0_11001_ignoreCallOp113() {
    ap_block_pp0_stage0_11001_ignoreCallOp113 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_pp0_stage0_11001_ignoreCallOp114() {
    ap_block_pp0_stage0_11001_ignoreCallOp114 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state1_pp0_stage0_iter0_ignore_call101() {
    ap_block_state1_pp0_stage0_iter0_ignore_call101 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state1_pp0_stage0_iter0_ignore_call102() {
    ap_block_state1_pp0_stage0_iter0_ignore_call102 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state1_pp0_stage0_iter0_ignore_call103() {
    ap_block_state1_pp0_stage0_iter0_ignore_call103 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state1_pp0_stage0_iter0_ignore_call106() {
    ap_block_state1_pp0_stage0_iter0_ignore_call106 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state1_pp0_stage0_iter0_ignore_call109() {
    ap_block_state1_pp0_stage0_iter0_ignore_call109 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state1_pp0_stage0_iter0_ignore_call112() {
    ap_block_state1_pp0_stage0_iter0_ignore_call112 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state1_pp0_stage0_iter0_ignore_call113() {
    ap_block_state1_pp0_stage0_iter0_ignore_call113 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state1_pp0_stage0_iter0_ignore_call114() {
    ap_block_state1_pp0_stage0_iter0_ignore_call114 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state1_pp0_stage0_iter0_ignore_call115() {
    ap_block_state1_pp0_stage0_iter0_ignore_call115 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state1_pp0_stage0_iter0_ignore_call116() {
    ap_block_state1_pp0_stage0_iter0_ignore_call116 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state2_pp0_stage0_iter1_ignore_call101() {
    ap_block_state2_pp0_stage0_iter1_ignore_call101 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state2_pp0_stage0_iter1_ignore_call102() {
    ap_block_state2_pp0_stage0_iter1_ignore_call102 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state2_pp0_stage0_iter1_ignore_call103() {
    ap_block_state2_pp0_stage0_iter1_ignore_call103 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state2_pp0_stage0_iter1_ignore_call106() {
    ap_block_state2_pp0_stage0_iter1_ignore_call106 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state2_pp0_stage0_iter1_ignore_call109() {
    ap_block_state2_pp0_stage0_iter1_ignore_call109 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state2_pp0_stage0_iter1_ignore_call112() {
    ap_block_state2_pp0_stage0_iter1_ignore_call112 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state2_pp0_stage0_iter1_ignore_call113() {
    ap_block_state2_pp0_stage0_iter1_ignore_call113 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state2_pp0_stage0_iter1_ignore_call114() {
    ap_block_state2_pp0_stage0_iter1_ignore_call114 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state2_pp0_stage0_iter1_ignore_call115() {
    ap_block_state2_pp0_stage0_iter1_ignore_call115 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state2_pp0_stage0_iter1_ignore_call116() {
    ap_block_state2_pp0_stage0_iter1_ignore_call116 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state3_pp0_stage0_iter2_ignore_call101() {
    ap_block_state3_pp0_stage0_iter2_ignore_call101 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state3_pp0_stage0_iter2_ignore_call102() {
    ap_block_state3_pp0_stage0_iter2_ignore_call102 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state3_pp0_stage0_iter2_ignore_call103() {
    ap_block_state3_pp0_stage0_iter2_ignore_call103 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state3_pp0_stage0_iter2_ignore_call106() {
    ap_block_state3_pp0_stage0_iter2_ignore_call106 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state3_pp0_stage0_iter2_ignore_call109() {
    ap_block_state3_pp0_stage0_iter2_ignore_call109 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state3_pp0_stage0_iter2_ignore_call112() {
    ap_block_state3_pp0_stage0_iter2_ignore_call112 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state3_pp0_stage0_iter2_ignore_call113() {
    ap_block_state3_pp0_stage0_iter2_ignore_call113 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state3_pp0_stage0_iter2_ignore_call114() {
    ap_block_state3_pp0_stage0_iter2_ignore_call114 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state3_pp0_stage0_iter2_ignore_call115() {
    ap_block_state3_pp0_stage0_iter2_ignore_call115 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state3_pp0_stage0_iter2_ignore_call116() {
    ap_block_state3_pp0_stage0_iter2_ignore_call116 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state4_pp0_stage0_iter3_ignore_call101() {
    ap_block_state4_pp0_stage0_iter3_ignore_call101 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state4_pp0_stage0_iter3_ignore_call102() {
    ap_block_state4_pp0_stage0_iter3_ignore_call102 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state4_pp0_stage0_iter3_ignore_call103() {
    ap_block_state4_pp0_stage0_iter3_ignore_call103 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state4_pp0_stage0_iter3_ignore_call106() {
    ap_block_state4_pp0_stage0_iter3_ignore_call106 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state4_pp0_stage0_iter3_ignore_call109() {
    ap_block_state4_pp0_stage0_iter3_ignore_call109 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state4_pp0_stage0_iter3_ignore_call112() {
    ap_block_state4_pp0_stage0_iter3_ignore_call112 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state4_pp0_stage0_iter3_ignore_call113() {
    ap_block_state4_pp0_stage0_iter3_ignore_call113 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state4_pp0_stage0_iter3_ignore_call114() {
    ap_block_state4_pp0_stage0_iter3_ignore_call114 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state4_pp0_stage0_iter3_ignore_call115() {
    ap_block_state4_pp0_stage0_iter3_ignore_call115 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_block_state4_pp0_stage0_iter3_ignore_call116() {
    ap_block_state4_pp0_stage0_iter3_ignore_call116 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = ap_start.read();
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_idle_pp0_0to2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0_0to2 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to2 = ap_const_logic_0;
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to2.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_return_0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        ap_return_0 = zext_ln728_fu_1066_p1.read();
    } else {
        ap_return_0 = ap_return_0_preg.read();
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_return_1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        ap_return_1 = zext_ln728_1_fu_1078_p1.read();
    } else {
        ap_return_1 = ap_return_1_preg.read();
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_return_2() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        ap_return_2 = zext_ln728_2_fu_1090_p1.read();
    } else {
        ap_return_2 = ap_return_2_preg.read();
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010_ap_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001_ignoreCallOp113.read(), ap_const_boolean_0))) {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010_ap_ce = ap_const_logic_1;
    } else {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1010_ap_ce = ap_const_logic_0;
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034_ap_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001_ignoreCallOp114.read(), ap_const_boolean_0))) {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034_ap_ce = ap_const_logic_1;
    } else {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_1034_ap_ce = ap_const_logic_0;
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818_ap_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001_ignoreCallOp105.read(), ap_const_boolean_0))) {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818_ap_ce = ap_const_logic_1;
    } else {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_818_ap_ce = ap_const_logic_0;
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842_ap_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001_ignoreCallOp106.read(), ap_const_boolean_0))) {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842_ap_ce = ap_const_logic_1;
    } else {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_842_ap_ce = ap_const_logic_0;
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866_ap_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001_ignoreCallOp107.read(), ap_const_boolean_0))) {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866_ap_ce = ap_const_logic_1;
    } else {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866_ap_ce = ap_const_logic_0;
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890_ap_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001_ignoreCallOp108.read(), ap_const_boolean_0))) {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890_ap_ce = ap_const_logic_1;
    } else {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890_ap_ce = ap_const_logic_0;
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914_ap_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001_ignoreCallOp109.read(), ap_const_boolean_0))) {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914_ap_ce = ap_const_logic_1;
    } else {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914_ap_ce = ap_const_logic_0;
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938_ap_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001_ignoreCallOp110.read(), ap_const_boolean_0))) {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938_ap_ce = ap_const_logic_1;
    } else {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_938_ap_ce = ap_const_logic_0;
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962_ap_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001_ignoreCallOp111.read(), ap_const_boolean_0))) {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962_ap_ce = ap_const_logic_1;
    } else {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_962_ap_ce = ap_const_logic_0;
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986_ap_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001_ignoreCallOp112.read(), ap_const_boolean_0))) {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986_ap_ce = ap_const_logic_1;
    } else {
        grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_986_ap_ce = ap_const_logic_0;
    }
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_res_2_V_write_assign_fu_1058_p3() {
    res_2_V_write_assign_fu_1058_p3 = esl_concat<5,2>(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_866_ap_return.read(), ap_const_lv2_0);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_res_3_V_write_assign_fu_1070_p3() {
    res_3_V_write_assign_fu_1070_p3 = esl_concat<5,2>(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_890_ap_return.read(), ap_const_lv2_0);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_res_4_V_write_assign_fu_1082_p3() {
    res_4_V_write_assign_fu_1082_p3 = esl_concat<5,2>(grp_pool_op_ap_ufixed_8_0_4_0_0_10_1_s_fu_914_ap_return.read(), ap_const_lv2_0);
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_zext_ln728_1_fu_1078_p1() {
    zext_ln728_1_fu_1078_p1 = esl_zext<10,7>(res_3_V_write_assign_fu_1070_p3.read());
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_zext_ln728_2_fu_1090_p1() {
    zext_ln728_2_fu_1090_p1 = esl_zext<10,7>(res_4_V_write_assign_fu_1082_p3.read());
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_zext_ln728_fu_1066_p1() {
    zext_ln728_fu_1066_p1 = esl_zext<10,7>(res_2_V_write_assign_fu_1058_p3.read());
}

void global_pooling1d_cl_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config8_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

