// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_ST_fsm_state1 = "1";
const sc_lv<2> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_ST_fsm_state2 = "10";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_1 = "1";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_A = "1010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_13 = "10011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_14 = "10100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_1D = "11101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_28 = "101000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_31 = "110001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_32 = "110010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_3B = "111011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_3C = "111100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_45 = "1000101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_46 = "1000110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_4F = "1001111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_50 = "1010000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_59 = "1011001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_5A = "1011010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_63 = "1100011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_64 = "1100100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_6D = "1101101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_6E = "1101110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_77 = "1110111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_8C = "10001100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_95 = "10010101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_96 = "10010110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_9F = "10011111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_A0 = "10100000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_A9 = "10101001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_B4 = "10110100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_BD = "10111101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_BE = "10111110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_C7 = "11000111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_C8 = "11001000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_D1 = "11010001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_D2 = "11010010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_DB = "11011011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_DC = "11011100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_E5 = "11100101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_E6 = "11100110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_EF = "11101111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_F0 = "11110000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_F9 = "11111001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_FA = "11111010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_103 = "100000011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_118 = "100011000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_121 = "100100001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_122 = "100100010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_12B = "100101011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_12C = "100101100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_135 = "100110101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_140 = "101000000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_149 = "101001001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_14A = "101001010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_153 = "101010011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_154 = "101010100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_15D = "101011101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_15E = "101011110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_167 = "101100111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_168 = "101101000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_171 = "101110001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_172 = "101110010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_17B = "101111011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_17C = "101111100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_185 = "110000101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_186 = "110000110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_18F = "110001111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_1A4 = "110100100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_1AD = "110101101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_1AE = "110101110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_1B7 = "110110111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_1B8 = "110111000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_1C1 = "111000001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_1CC = "111001100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_1D5 = "111010101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_1D6 = "111010110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_1DF = "111011111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_1E0 = "111100000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_1E9 = "111101001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_1EA = "111101010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_1F3 = "111110011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_1F4 = "111110100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_1FD = "111111101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_1FE = "111111110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_207 = "1000000111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_208 = "1000001000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_211 = "1000010001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_212 = "1000010010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_21B = "1000011011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_230 = "1000110000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_239 = "1000111001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_23A = "1000111010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_243 = "1001000011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_244 = "1001000100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_24D = "1001001101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_258 = "1001011000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_261 = "1001100001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_262 = "1001100010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_26B = "1001101011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_26C = "1001101100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_275 = "1001110101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_276 = "1001110110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_27F = "1001111111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_280 = "1010000000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_289 = "1010001001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_28A = "1010001010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_293 = "1010010011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_294 = "1010010100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_29D = "1010011101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_29E = "1010011110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_2A7 = "1010100111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_2BC = "1010111100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_2C5 = "1011000101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_2C6 = "1011000110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_2CF = "1011001111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_2D0 = "1011010000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_2D9 = "1011011001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_2E4 = "1011100100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_2ED = "1011101101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_2EE = "1011101110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_2F7 = "1011110111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_2F8 = "1011111000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_301 = "1100000001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_302 = "1100000010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_30B = "1100001011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_30C = "1100001100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_315 = "1100010101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_316 = "1100010110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_31F = "1100011111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_320 = "1100100000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_329 = "1100101001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_32A = "1100101010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_333 = "1100110011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_348 = "1101001000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_351 = "1101010001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_352 = "1101010010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_35B = "1101011011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_35C = "1101011100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_365 = "1101100101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_370 = "1101110000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_379 = "1101111001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_37A = "1101111010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_383 = "1110000011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_384 = "1110000100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_38D = "1110001101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_38E = "1110001110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_397 = "1110010111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_398 = "1110011000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_3A1 = "1110100001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_3A2 = "1110100010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_3AB = "1110101011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_3AC = "1110101100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_3B5 = "1110110101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_3B6 = "1110110110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_3BF = "1110111111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_3D4 = "1111010100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_3DD = "1111011101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_3DE = "1111011110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_3E7 = "1111100111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_3E8 = "1111101000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_3F1 = "1111110001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_3FC = "1111111100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_405 = "10000000101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_406 = "10000000110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_40F = "10000001111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_410 = "10000010000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_419 = "10000011001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_41A = "10000011010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_423 = "10000100011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_424 = "10000100100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_42D = "10000101101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_42E = "10000101110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_437 = "10000110111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_438 = "10000111000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_441 = "10001000001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_442 = "10001000010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_44B = "10001001011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_460 = "10001100000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_469 = "10001101001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_46A = "10001101010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_473 = "10001110011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_474 = "10001110100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_47D = "10001111101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_488 = "10010001000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_491 = "10010010001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_492 = "10010010010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_49B = "10010011011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_49C = "10010011100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_4A5 = "10010100101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_4A6 = "10010100110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_4AF = "10010101111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_4B0 = "10010110000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_4B9 = "10010111001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_4BA = "10010111010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_4C3 = "10011000011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_4C4 = "10011000100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_4CD = "10011001101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_4CE = "10011001110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_4D7 = "10011010111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_4EC = "10011101100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_4F5 = "10011110101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_4F6 = "10011110110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_4FF = "10011111111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_500 = "10100000000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_509 = "10100001001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_514 = "10100010100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_51D = "10100011101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_51E = "10100011110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_527 = "10100100111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_528 = "10100101000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_531 = "10100110001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_532 = "10100110010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_53B = "10100111011";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_53C = "10100111100";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_545 = "10101000101";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_546 = "10101000110";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_54F = "10101001111";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_550 = "10101010000";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_559 = "10101011001";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_55A = "10101011010";
const sc_lv<32> pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_lv32_563 = "10101100011";
const bool pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::ap_const_boolean_1 = true;

pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466 = new pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1("call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466");
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->ap_ready(call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_ready);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read(data_tmp_0_0_V_reg_1978);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read1(data_tmp_0_1_V_reg_1983);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read2(data_tmp_0_2_V_reg_1988);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read3(data_tmp_0_4_V_reg_1993);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read4(data_tmp_0_5_V_reg_1998);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read5(data_tmp_0_6_V_reg_2003);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read6(data_tmp_0_7_V_reg_2008);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read7(data_tmp_0_8_V_reg_2013);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read8(data_tmp_0_9_V_reg_2018);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read9(data_tmp_0_10_V_reg_2023);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read10(data_tmp_0_11_V_reg_2028);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read11(data_tmp_0_14_V_reg_2033);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read12(data_tmp_0_15_V_reg_2038);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read13(data_tmp_0_16_V_reg_2043);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read14(data_tmp_0_18_V_reg_2048);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read15(data_tmp_0_19_V_reg_2053);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read16(data_tmp_0_20_V_reg_2058);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read17(data_tmp_0_21_V_reg_2063);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read18(data_tmp_0_22_V_reg_2068);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read19(data_tmp_0_23_V_reg_2073);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read20(data_tmp_0_24_V_reg_2078);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read21(data_tmp_0_25_V_reg_2083);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read22(data_tmp_0_28_V_reg_2088);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read23(data_tmp_0_29_V_reg_2093);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read24(data_tmp_0_30_V_reg_2098);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read25(data_tmp_0_32_V_reg_2103);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read26(data_tmp_0_33_V_reg_2108);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read27(data_tmp_0_34_V_reg_2113);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read28(data_tmp_0_35_V_reg_2118);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read29(data_tmp_0_36_V_reg_2123);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read30(data_tmp_0_37_V_reg_2128);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read31(data_tmp_0_38_V_reg_2133);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read32(data_tmp_0_39_V_reg_2138);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read33(data_tmp_0_42_V_reg_2143);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read34(data_tmp_0_43_V_reg_2148);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read35(data_tmp_0_44_V_reg_2153);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read36(data_tmp_0_46_V_reg_2158);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read37(data_tmp_0_47_V_reg_2163);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read38(data_tmp_0_48_V_reg_2168);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read39(data_tmp_0_49_V_reg_2173);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read40(data_tmp_0_50_V_reg_2178);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read41(data_tmp_0_51_V_reg_2183);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read42(data_tmp_0_52_V_reg_2188);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read43(data_tmp_0_53_V_reg_2193);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read44(data_tmp_0_56_V_reg_2198);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read45(data_tmp_0_57_V_reg_2203);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read46(data_tmp_0_58_V_reg_2208);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read47(data_tmp_0_60_V_reg_2213);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read48(data_tmp_0_61_V_reg_2218);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read49(data_tmp_0_62_V_reg_2223);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read50(data_tmp_0_63_V_reg_2228);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read51(data_tmp_0_64_V_reg_2233);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read52(data_tmp_0_65_V_reg_2238);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read53(data_tmp_0_66_V_reg_2243);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->p_read54(data_tmp_0_67_V_reg_2248);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->ap_return_0(call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_0);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->ap_return_1(call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_1);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->ap_return_2(call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_2);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->ap_return_3(call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_3);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->ap_return_4(call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_4);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->ap_return_5(call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_5);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->ap_return_6(call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_6);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->ap_return_7(call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_7);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->ap_return_8(call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_8);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->ap_return_9(call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_9);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->ap_return_10(call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_10);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->ap_return_11(call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_11);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->ap_return_12(call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_12);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->ap_return_13(call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_13);
    call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466->ap_return_14(call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_14);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525 = new pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1("call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525");
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->ap_ready(call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_ready);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read(data_tmp_1_0_V_reg_2253);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read1(data_tmp_1_1_V_reg_2258);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read2(data_tmp_1_2_V_reg_2263);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read3(data_tmp_1_4_V_reg_2268);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read4(data_tmp_1_5_V_reg_2273);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read5(data_tmp_1_6_V_reg_2278);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read6(data_tmp_1_7_V_reg_2283);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read7(data_tmp_1_8_V_reg_2288);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read8(data_tmp_1_9_V_reg_2293);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read9(data_tmp_1_10_V_reg_2298);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read10(data_tmp_1_11_V_reg_2303);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read11(data_tmp_1_14_V_reg_2308);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read12(data_tmp_1_15_V_reg_2313);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read13(data_tmp_1_16_V_reg_2318);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read14(data_tmp_1_18_V_reg_2323);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read15(data_tmp_1_19_V_reg_2328);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read16(data_tmp_1_20_V_reg_2333);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read17(data_tmp_1_21_V_reg_2338);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read18(data_tmp_1_22_V_reg_2343);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read19(data_tmp_1_23_V_reg_2348);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read20(data_tmp_1_24_V_reg_2353);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read21(data_tmp_1_25_V_reg_2358);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read22(data_tmp_1_28_V_reg_2363);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read23(data_tmp_1_29_V_reg_2368);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read24(data_tmp_1_30_V_reg_2373);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read25(data_tmp_1_32_V_reg_2378);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read26(data_tmp_1_33_V_reg_2383);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read27(data_tmp_1_34_V_reg_2388);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read28(data_tmp_1_35_V_reg_2393);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read29(data_tmp_1_36_V_reg_2398);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read30(data_tmp_1_37_V_reg_2403);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read31(data_tmp_1_38_V_reg_2408);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read32(data_tmp_1_39_V_reg_2413);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read33(data_tmp_1_42_V_reg_2418);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read34(data_tmp_1_43_V_reg_2423);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read35(data_tmp_1_44_V_reg_2428);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read36(data_tmp_1_46_V_reg_2433);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read37(data_tmp_1_47_V_reg_2438);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read38(data_tmp_1_48_V_reg_2443);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read39(data_tmp_1_49_V_reg_2448);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read40(data_tmp_1_50_V_reg_2453);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read41(data_tmp_1_51_V_reg_2458);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read42(data_tmp_1_52_V_reg_2463);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read43(data_tmp_1_53_V_reg_2468);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read44(data_tmp_1_56_V_reg_2473);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read45(data_tmp_1_57_V_reg_2478);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read46(data_tmp_1_58_V_reg_2483);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read47(data_tmp_1_60_V_reg_2488);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read48(data_tmp_1_61_V_reg_2493);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read49(data_tmp_1_62_V_reg_2498);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read50(data_tmp_1_63_V_reg_2503);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read51(data_tmp_1_64_V_reg_2508);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read52(data_tmp_1_65_V_reg_2513);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read53(data_tmp_1_66_V_reg_2518);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->p_read54(data_tmp_1_67_V_reg_2523);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->ap_return_0(call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_0);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->ap_return_1(call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_1);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->ap_return_2(call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_2);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->ap_return_3(call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_3);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->ap_return_4(call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_4);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->ap_return_5(call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_5);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->ap_return_6(call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_6);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->ap_return_7(call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_7);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->ap_return_8(call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_8);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->ap_return_9(call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_9);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->ap_return_10(call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_10);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->ap_return_11(call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_11);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->ap_return_12(call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_12);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->ap_return_13(call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_13);
    call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525->ap_return_14(call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_14);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( data_V_empty_n );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_10);
    sensitive << ( call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_10 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_11);
    sensitive << ( call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_11 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_12);
    sensitive << ( call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_12 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_13);
    sensitive << ( call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_13 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_14);
    sensitive << ( call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_14 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_15);
    sensitive << ( call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_16);
    sensitive << ( call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_17);
    sensitive << ( call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_18);
    sensitive << ( call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_3 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_19);
    sensitive << ( call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_4 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_20);
    sensitive << ( call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_5 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_21);
    sensitive << ( call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_6 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_22);
    sensitive << ( call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_7 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_23);
    sensitive << ( call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_8 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_24);
    sensitive << ( call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_9 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_25);
    sensitive << ( call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_10 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_26);
    sensitive << ( call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_11 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_27);
    sensitive << ( call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_12 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_28);
    sensitive << ( call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_13 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_29);
    sensitive << ( call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_14 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_3 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_4 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_5 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_6 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_7);
    sensitive << ( call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_7 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_8);
    sensitive << ( call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_8 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_9);
    sensitive << ( call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_9 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_data_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_empty_n );

    SC_METHOD(thread_data_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_empty_n );

    SC_METHOD(thread_data_tmp_0_0_V_fu_584_p1);
    sensitive << ( data_V_dout );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_empty_n );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "01";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_V_dout, "(port)data_V_dout");
    sc_trace(mVcdFile, data_V_empty_n, "(port)data_V_empty_n");
    sc_trace(mVcdFile, data_V_read, "(port)data_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, ap_return_7, "(port)ap_return_7");
    sc_trace(mVcdFile, ap_return_8, "(port)ap_return_8");
    sc_trace(mVcdFile, ap_return_9, "(port)ap_return_9");
    sc_trace(mVcdFile, ap_return_10, "(port)ap_return_10");
    sc_trace(mVcdFile, ap_return_11, "(port)ap_return_11");
    sc_trace(mVcdFile, ap_return_12, "(port)ap_return_12");
    sc_trace(mVcdFile, ap_return_13, "(port)ap_return_13");
    sc_trace(mVcdFile, ap_return_14, "(port)ap_return_14");
    sc_trace(mVcdFile, ap_return_15, "(port)ap_return_15");
    sc_trace(mVcdFile, ap_return_16, "(port)ap_return_16");
    sc_trace(mVcdFile, ap_return_17, "(port)ap_return_17");
    sc_trace(mVcdFile, ap_return_18, "(port)ap_return_18");
    sc_trace(mVcdFile, ap_return_19, "(port)ap_return_19");
    sc_trace(mVcdFile, ap_return_20, "(port)ap_return_20");
    sc_trace(mVcdFile, ap_return_21, "(port)ap_return_21");
    sc_trace(mVcdFile, ap_return_22, "(port)ap_return_22");
    sc_trace(mVcdFile, ap_return_23, "(port)ap_return_23");
    sc_trace(mVcdFile, ap_return_24, "(port)ap_return_24");
    sc_trace(mVcdFile, ap_return_25, "(port)ap_return_25");
    sc_trace(mVcdFile, ap_return_26, "(port)ap_return_26");
    sc_trace(mVcdFile, ap_return_27, "(port)ap_return_27");
    sc_trace(mVcdFile, ap_return_28, "(port)ap_return_28");
    sc_trace(mVcdFile, ap_return_29, "(port)ap_return_29");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, data_V_blk_n, "data_V_blk_n");
    sc_trace(mVcdFile, data_tmp_0_0_V_fu_584_p1, "data_tmp_0_0_V_fu_584_p1");
    sc_trace(mVcdFile, data_tmp_0_0_V_reg_1978, "data_tmp_0_0_V_reg_1978");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, data_tmp_0_1_V_reg_1983, "data_tmp_0_1_V_reg_1983");
    sc_trace(mVcdFile, data_tmp_0_2_V_reg_1988, "data_tmp_0_2_V_reg_1988");
    sc_trace(mVcdFile, data_tmp_0_4_V_reg_1993, "data_tmp_0_4_V_reg_1993");
    sc_trace(mVcdFile, data_tmp_0_5_V_reg_1998, "data_tmp_0_5_V_reg_1998");
    sc_trace(mVcdFile, data_tmp_0_6_V_reg_2003, "data_tmp_0_6_V_reg_2003");
    sc_trace(mVcdFile, data_tmp_0_7_V_reg_2008, "data_tmp_0_7_V_reg_2008");
    sc_trace(mVcdFile, data_tmp_0_8_V_reg_2013, "data_tmp_0_8_V_reg_2013");
    sc_trace(mVcdFile, data_tmp_0_9_V_reg_2018, "data_tmp_0_9_V_reg_2018");
    sc_trace(mVcdFile, data_tmp_0_10_V_reg_2023, "data_tmp_0_10_V_reg_2023");
    sc_trace(mVcdFile, data_tmp_0_11_V_reg_2028, "data_tmp_0_11_V_reg_2028");
    sc_trace(mVcdFile, data_tmp_0_14_V_reg_2033, "data_tmp_0_14_V_reg_2033");
    sc_trace(mVcdFile, data_tmp_0_15_V_reg_2038, "data_tmp_0_15_V_reg_2038");
    sc_trace(mVcdFile, data_tmp_0_16_V_reg_2043, "data_tmp_0_16_V_reg_2043");
    sc_trace(mVcdFile, data_tmp_0_18_V_reg_2048, "data_tmp_0_18_V_reg_2048");
    sc_trace(mVcdFile, data_tmp_0_19_V_reg_2053, "data_tmp_0_19_V_reg_2053");
    sc_trace(mVcdFile, data_tmp_0_20_V_reg_2058, "data_tmp_0_20_V_reg_2058");
    sc_trace(mVcdFile, data_tmp_0_21_V_reg_2063, "data_tmp_0_21_V_reg_2063");
    sc_trace(mVcdFile, data_tmp_0_22_V_reg_2068, "data_tmp_0_22_V_reg_2068");
    sc_trace(mVcdFile, data_tmp_0_23_V_reg_2073, "data_tmp_0_23_V_reg_2073");
    sc_trace(mVcdFile, data_tmp_0_24_V_reg_2078, "data_tmp_0_24_V_reg_2078");
    sc_trace(mVcdFile, data_tmp_0_25_V_reg_2083, "data_tmp_0_25_V_reg_2083");
    sc_trace(mVcdFile, data_tmp_0_28_V_reg_2088, "data_tmp_0_28_V_reg_2088");
    sc_trace(mVcdFile, data_tmp_0_29_V_reg_2093, "data_tmp_0_29_V_reg_2093");
    sc_trace(mVcdFile, data_tmp_0_30_V_reg_2098, "data_tmp_0_30_V_reg_2098");
    sc_trace(mVcdFile, data_tmp_0_32_V_reg_2103, "data_tmp_0_32_V_reg_2103");
    sc_trace(mVcdFile, data_tmp_0_33_V_reg_2108, "data_tmp_0_33_V_reg_2108");
    sc_trace(mVcdFile, data_tmp_0_34_V_reg_2113, "data_tmp_0_34_V_reg_2113");
    sc_trace(mVcdFile, data_tmp_0_35_V_reg_2118, "data_tmp_0_35_V_reg_2118");
    sc_trace(mVcdFile, data_tmp_0_36_V_reg_2123, "data_tmp_0_36_V_reg_2123");
    sc_trace(mVcdFile, data_tmp_0_37_V_reg_2128, "data_tmp_0_37_V_reg_2128");
    sc_trace(mVcdFile, data_tmp_0_38_V_reg_2133, "data_tmp_0_38_V_reg_2133");
    sc_trace(mVcdFile, data_tmp_0_39_V_reg_2138, "data_tmp_0_39_V_reg_2138");
    sc_trace(mVcdFile, data_tmp_0_42_V_reg_2143, "data_tmp_0_42_V_reg_2143");
    sc_trace(mVcdFile, data_tmp_0_43_V_reg_2148, "data_tmp_0_43_V_reg_2148");
    sc_trace(mVcdFile, data_tmp_0_44_V_reg_2153, "data_tmp_0_44_V_reg_2153");
    sc_trace(mVcdFile, data_tmp_0_46_V_reg_2158, "data_tmp_0_46_V_reg_2158");
    sc_trace(mVcdFile, data_tmp_0_47_V_reg_2163, "data_tmp_0_47_V_reg_2163");
    sc_trace(mVcdFile, data_tmp_0_48_V_reg_2168, "data_tmp_0_48_V_reg_2168");
    sc_trace(mVcdFile, data_tmp_0_49_V_reg_2173, "data_tmp_0_49_V_reg_2173");
    sc_trace(mVcdFile, data_tmp_0_50_V_reg_2178, "data_tmp_0_50_V_reg_2178");
    sc_trace(mVcdFile, data_tmp_0_51_V_reg_2183, "data_tmp_0_51_V_reg_2183");
    sc_trace(mVcdFile, data_tmp_0_52_V_reg_2188, "data_tmp_0_52_V_reg_2188");
    sc_trace(mVcdFile, data_tmp_0_53_V_reg_2193, "data_tmp_0_53_V_reg_2193");
    sc_trace(mVcdFile, data_tmp_0_56_V_reg_2198, "data_tmp_0_56_V_reg_2198");
    sc_trace(mVcdFile, data_tmp_0_57_V_reg_2203, "data_tmp_0_57_V_reg_2203");
    sc_trace(mVcdFile, data_tmp_0_58_V_reg_2208, "data_tmp_0_58_V_reg_2208");
    sc_trace(mVcdFile, data_tmp_0_60_V_reg_2213, "data_tmp_0_60_V_reg_2213");
    sc_trace(mVcdFile, data_tmp_0_61_V_reg_2218, "data_tmp_0_61_V_reg_2218");
    sc_trace(mVcdFile, data_tmp_0_62_V_reg_2223, "data_tmp_0_62_V_reg_2223");
    sc_trace(mVcdFile, data_tmp_0_63_V_reg_2228, "data_tmp_0_63_V_reg_2228");
    sc_trace(mVcdFile, data_tmp_0_64_V_reg_2233, "data_tmp_0_64_V_reg_2233");
    sc_trace(mVcdFile, data_tmp_0_65_V_reg_2238, "data_tmp_0_65_V_reg_2238");
    sc_trace(mVcdFile, data_tmp_0_66_V_reg_2243, "data_tmp_0_66_V_reg_2243");
    sc_trace(mVcdFile, data_tmp_0_67_V_reg_2248, "data_tmp_0_67_V_reg_2248");
    sc_trace(mVcdFile, data_tmp_1_0_V_reg_2253, "data_tmp_1_0_V_reg_2253");
    sc_trace(mVcdFile, data_tmp_1_1_V_reg_2258, "data_tmp_1_1_V_reg_2258");
    sc_trace(mVcdFile, data_tmp_1_2_V_reg_2263, "data_tmp_1_2_V_reg_2263");
    sc_trace(mVcdFile, data_tmp_1_4_V_reg_2268, "data_tmp_1_4_V_reg_2268");
    sc_trace(mVcdFile, data_tmp_1_5_V_reg_2273, "data_tmp_1_5_V_reg_2273");
    sc_trace(mVcdFile, data_tmp_1_6_V_reg_2278, "data_tmp_1_6_V_reg_2278");
    sc_trace(mVcdFile, data_tmp_1_7_V_reg_2283, "data_tmp_1_7_V_reg_2283");
    sc_trace(mVcdFile, data_tmp_1_8_V_reg_2288, "data_tmp_1_8_V_reg_2288");
    sc_trace(mVcdFile, data_tmp_1_9_V_reg_2293, "data_tmp_1_9_V_reg_2293");
    sc_trace(mVcdFile, data_tmp_1_10_V_reg_2298, "data_tmp_1_10_V_reg_2298");
    sc_trace(mVcdFile, data_tmp_1_11_V_reg_2303, "data_tmp_1_11_V_reg_2303");
    sc_trace(mVcdFile, data_tmp_1_14_V_reg_2308, "data_tmp_1_14_V_reg_2308");
    sc_trace(mVcdFile, data_tmp_1_15_V_reg_2313, "data_tmp_1_15_V_reg_2313");
    sc_trace(mVcdFile, data_tmp_1_16_V_reg_2318, "data_tmp_1_16_V_reg_2318");
    sc_trace(mVcdFile, data_tmp_1_18_V_reg_2323, "data_tmp_1_18_V_reg_2323");
    sc_trace(mVcdFile, data_tmp_1_19_V_reg_2328, "data_tmp_1_19_V_reg_2328");
    sc_trace(mVcdFile, data_tmp_1_20_V_reg_2333, "data_tmp_1_20_V_reg_2333");
    sc_trace(mVcdFile, data_tmp_1_21_V_reg_2338, "data_tmp_1_21_V_reg_2338");
    sc_trace(mVcdFile, data_tmp_1_22_V_reg_2343, "data_tmp_1_22_V_reg_2343");
    sc_trace(mVcdFile, data_tmp_1_23_V_reg_2348, "data_tmp_1_23_V_reg_2348");
    sc_trace(mVcdFile, data_tmp_1_24_V_reg_2353, "data_tmp_1_24_V_reg_2353");
    sc_trace(mVcdFile, data_tmp_1_25_V_reg_2358, "data_tmp_1_25_V_reg_2358");
    sc_trace(mVcdFile, data_tmp_1_28_V_reg_2363, "data_tmp_1_28_V_reg_2363");
    sc_trace(mVcdFile, data_tmp_1_29_V_reg_2368, "data_tmp_1_29_V_reg_2368");
    sc_trace(mVcdFile, data_tmp_1_30_V_reg_2373, "data_tmp_1_30_V_reg_2373");
    sc_trace(mVcdFile, data_tmp_1_32_V_reg_2378, "data_tmp_1_32_V_reg_2378");
    sc_trace(mVcdFile, data_tmp_1_33_V_reg_2383, "data_tmp_1_33_V_reg_2383");
    sc_trace(mVcdFile, data_tmp_1_34_V_reg_2388, "data_tmp_1_34_V_reg_2388");
    sc_trace(mVcdFile, data_tmp_1_35_V_reg_2393, "data_tmp_1_35_V_reg_2393");
    sc_trace(mVcdFile, data_tmp_1_36_V_reg_2398, "data_tmp_1_36_V_reg_2398");
    sc_trace(mVcdFile, data_tmp_1_37_V_reg_2403, "data_tmp_1_37_V_reg_2403");
    sc_trace(mVcdFile, data_tmp_1_38_V_reg_2408, "data_tmp_1_38_V_reg_2408");
    sc_trace(mVcdFile, data_tmp_1_39_V_reg_2413, "data_tmp_1_39_V_reg_2413");
    sc_trace(mVcdFile, data_tmp_1_42_V_reg_2418, "data_tmp_1_42_V_reg_2418");
    sc_trace(mVcdFile, data_tmp_1_43_V_reg_2423, "data_tmp_1_43_V_reg_2423");
    sc_trace(mVcdFile, data_tmp_1_44_V_reg_2428, "data_tmp_1_44_V_reg_2428");
    sc_trace(mVcdFile, data_tmp_1_46_V_reg_2433, "data_tmp_1_46_V_reg_2433");
    sc_trace(mVcdFile, data_tmp_1_47_V_reg_2438, "data_tmp_1_47_V_reg_2438");
    sc_trace(mVcdFile, data_tmp_1_48_V_reg_2443, "data_tmp_1_48_V_reg_2443");
    sc_trace(mVcdFile, data_tmp_1_49_V_reg_2448, "data_tmp_1_49_V_reg_2448");
    sc_trace(mVcdFile, data_tmp_1_50_V_reg_2453, "data_tmp_1_50_V_reg_2453");
    sc_trace(mVcdFile, data_tmp_1_51_V_reg_2458, "data_tmp_1_51_V_reg_2458");
    sc_trace(mVcdFile, data_tmp_1_52_V_reg_2463, "data_tmp_1_52_V_reg_2463");
    sc_trace(mVcdFile, data_tmp_1_53_V_reg_2468, "data_tmp_1_53_V_reg_2468");
    sc_trace(mVcdFile, data_tmp_1_56_V_reg_2473, "data_tmp_1_56_V_reg_2473");
    sc_trace(mVcdFile, data_tmp_1_57_V_reg_2478, "data_tmp_1_57_V_reg_2478");
    sc_trace(mVcdFile, data_tmp_1_58_V_reg_2483, "data_tmp_1_58_V_reg_2483");
    sc_trace(mVcdFile, data_tmp_1_60_V_reg_2488, "data_tmp_1_60_V_reg_2488");
    sc_trace(mVcdFile, data_tmp_1_61_V_reg_2493, "data_tmp_1_61_V_reg_2493");
    sc_trace(mVcdFile, data_tmp_1_62_V_reg_2498, "data_tmp_1_62_V_reg_2498");
    sc_trace(mVcdFile, data_tmp_1_63_V_reg_2503, "data_tmp_1_63_V_reg_2503");
    sc_trace(mVcdFile, data_tmp_1_64_V_reg_2508, "data_tmp_1_64_V_reg_2508");
    sc_trace(mVcdFile, data_tmp_1_65_V_reg_2513, "data_tmp_1_65_V_reg_2513");
    sc_trace(mVcdFile, data_tmp_1_66_V_reg_2518, "data_tmp_1_66_V_reg_2518");
    sc_trace(mVcdFile, data_tmp_1_67_V_reg_2523, "data_tmp_1_67_V_reg_2523");
    sc_trace(mVcdFile, call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_ready, "call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_ready");
    sc_trace(mVcdFile, call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_0, "call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_0");
    sc_trace(mVcdFile, call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_1, "call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_1");
    sc_trace(mVcdFile, call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_2, "call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_2");
    sc_trace(mVcdFile, call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_3, "call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_3");
    sc_trace(mVcdFile, call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_4, "call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_4");
    sc_trace(mVcdFile, call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_5, "call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_5");
    sc_trace(mVcdFile, call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_6, "call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_6");
    sc_trace(mVcdFile, call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_7, "call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_7");
    sc_trace(mVcdFile, call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_8, "call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_8");
    sc_trace(mVcdFile, call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_9, "call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_9");
    sc_trace(mVcdFile, call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_10, "call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_10");
    sc_trace(mVcdFile, call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_11, "call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_11");
    sc_trace(mVcdFile, call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_12, "call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_12");
    sc_trace(mVcdFile, call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_13, "call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_13");
    sc_trace(mVcdFile, call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_14, "call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_14");
    sc_trace(mVcdFile, call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_ready, "call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_ready");
    sc_trace(mVcdFile, call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_0, "call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_0");
    sc_trace(mVcdFile, call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_1, "call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_1");
    sc_trace(mVcdFile, call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_2, "call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_2");
    sc_trace(mVcdFile, call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_3, "call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_3");
    sc_trace(mVcdFile, call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_4, "call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_4");
    sc_trace(mVcdFile, call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_5, "call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_5");
    sc_trace(mVcdFile, call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_6, "call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_6");
    sc_trace(mVcdFile, call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_7, "call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_7");
    sc_trace(mVcdFile, call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_8, "call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_8");
    sc_trace(mVcdFile, call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_9, "call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_9");
    sc_trace(mVcdFile, call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_10, "call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_10");
    sc_trace(mVcdFile, call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_11, "call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_11");
    sc_trace(mVcdFile, call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_12, "call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_12");
    sc_trace(mVcdFile, call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_13, "call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_13");
    sc_trace(mVcdFile, call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_14, "call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_14");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::~pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466;
    delete call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525;
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, data_V_empty_n.read())))) {
        data_tmp_0_0_V_reg_1978 = data_tmp_0_0_V_fu_584_p1.read();
        data_tmp_0_10_V_reg_2023 = data_V_dout.read().range(109, 100);
        data_tmp_0_11_V_reg_2028 = data_V_dout.read().range(119, 110);
        data_tmp_0_14_V_reg_2033 = data_V_dout.read().range(149, 140);
        data_tmp_0_15_V_reg_2038 = data_V_dout.read().range(159, 150);
        data_tmp_0_16_V_reg_2043 = data_V_dout.read().range(169, 160);
        data_tmp_0_18_V_reg_2048 = data_V_dout.read().range(189, 180);
        data_tmp_0_19_V_reg_2053 = data_V_dout.read().range(199, 190);
        data_tmp_0_1_V_reg_1983 = data_V_dout.read().range(19, 10);
        data_tmp_0_20_V_reg_2058 = data_V_dout.read().range(209, 200);
        data_tmp_0_21_V_reg_2063 = data_V_dout.read().range(219, 210);
        data_tmp_0_22_V_reg_2068 = data_V_dout.read().range(229, 220);
        data_tmp_0_23_V_reg_2073 = data_V_dout.read().range(239, 230);
        data_tmp_0_24_V_reg_2078 = data_V_dout.read().range(249, 240);
        data_tmp_0_25_V_reg_2083 = data_V_dout.read().range(259, 250);
        data_tmp_0_28_V_reg_2088 = data_V_dout.read().range(289, 280);
        data_tmp_0_29_V_reg_2093 = data_V_dout.read().range(299, 290);
        data_tmp_0_2_V_reg_1988 = data_V_dout.read().range(29, 20);
        data_tmp_0_30_V_reg_2098 = data_V_dout.read().range(309, 300);
        data_tmp_0_32_V_reg_2103 = data_V_dout.read().range(329, 320);
        data_tmp_0_33_V_reg_2108 = data_V_dout.read().range(339, 330);
        data_tmp_0_34_V_reg_2113 = data_V_dout.read().range(349, 340);
        data_tmp_0_35_V_reg_2118 = data_V_dout.read().range(359, 350);
        data_tmp_0_36_V_reg_2123 = data_V_dout.read().range(369, 360);
        data_tmp_0_37_V_reg_2128 = data_V_dout.read().range(379, 370);
        data_tmp_0_38_V_reg_2133 = data_V_dout.read().range(389, 380);
        data_tmp_0_39_V_reg_2138 = data_V_dout.read().range(399, 390);
        data_tmp_0_42_V_reg_2143 = data_V_dout.read().range(429, 420);
        data_tmp_0_43_V_reg_2148 = data_V_dout.read().range(439, 430);
        data_tmp_0_44_V_reg_2153 = data_V_dout.read().range(449, 440);
        data_tmp_0_46_V_reg_2158 = data_V_dout.read().range(469, 460);
        data_tmp_0_47_V_reg_2163 = data_V_dout.read().range(479, 470);
        data_tmp_0_48_V_reg_2168 = data_V_dout.read().range(489, 480);
        data_tmp_0_49_V_reg_2173 = data_V_dout.read().range(499, 490);
        data_tmp_0_4_V_reg_1993 = data_V_dout.read().range(49, 40);
        data_tmp_0_50_V_reg_2178 = data_V_dout.read().range(509, 500);
        data_tmp_0_51_V_reg_2183 = data_V_dout.read().range(519, 510);
        data_tmp_0_52_V_reg_2188 = data_V_dout.read().range(529, 520);
        data_tmp_0_53_V_reg_2193 = data_V_dout.read().range(539, 530);
        data_tmp_0_56_V_reg_2198 = data_V_dout.read().range(569, 560);
        data_tmp_0_57_V_reg_2203 = data_V_dout.read().range(579, 570);
        data_tmp_0_58_V_reg_2208 = data_V_dout.read().range(589, 580);
        data_tmp_0_5_V_reg_1998 = data_V_dout.read().range(59, 50);
        data_tmp_0_60_V_reg_2213 = data_V_dout.read().range(609, 600);
        data_tmp_0_61_V_reg_2218 = data_V_dout.read().range(619, 610);
        data_tmp_0_62_V_reg_2223 = data_V_dout.read().range(629, 620);
        data_tmp_0_63_V_reg_2228 = data_V_dout.read().range(639, 630);
        data_tmp_0_64_V_reg_2233 = data_V_dout.read().range(649, 640);
        data_tmp_0_65_V_reg_2238 = data_V_dout.read().range(659, 650);
        data_tmp_0_66_V_reg_2243 = data_V_dout.read().range(669, 660);
        data_tmp_0_67_V_reg_2248 = data_V_dout.read().range(679, 670);
        data_tmp_0_6_V_reg_2003 = data_V_dout.read().range(69, 60);
        data_tmp_0_7_V_reg_2008 = data_V_dout.read().range(79, 70);
        data_tmp_0_8_V_reg_2013 = data_V_dout.read().range(89, 80);
        data_tmp_0_9_V_reg_2018 = data_V_dout.read().range(99, 90);
        data_tmp_1_0_V_reg_2253 = data_V_dout.read().range(709, 700);
        data_tmp_1_10_V_reg_2298 = data_V_dout.read().range(809, 800);
        data_tmp_1_11_V_reg_2303 = data_V_dout.read().range(819, 810);
        data_tmp_1_14_V_reg_2308 = data_V_dout.read().range(849, 840);
        data_tmp_1_15_V_reg_2313 = data_V_dout.read().range(859, 850);
        data_tmp_1_16_V_reg_2318 = data_V_dout.read().range(869, 860);
        data_tmp_1_18_V_reg_2323 = data_V_dout.read().range(889, 880);
        data_tmp_1_19_V_reg_2328 = data_V_dout.read().range(899, 890);
        data_tmp_1_1_V_reg_2258 = data_V_dout.read().range(719, 710);
        data_tmp_1_20_V_reg_2333 = data_V_dout.read().range(909, 900);
        data_tmp_1_21_V_reg_2338 = data_V_dout.read().range(919, 910);
        data_tmp_1_22_V_reg_2343 = data_V_dout.read().range(929, 920);
        data_tmp_1_23_V_reg_2348 = data_V_dout.read().range(939, 930);
        data_tmp_1_24_V_reg_2353 = data_V_dout.read().range(949, 940);
        data_tmp_1_25_V_reg_2358 = data_V_dout.read().range(959, 950);
        data_tmp_1_28_V_reg_2363 = data_V_dout.read().range(989, 980);
        data_tmp_1_29_V_reg_2368 = data_V_dout.read().range(999, 990);
        data_tmp_1_2_V_reg_2263 = data_V_dout.read().range(729, 720);
        data_tmp_1_30_V_reg_2373 = data_V_dout.read().range(1009, 1000);
        data_tmp_1_32_V_reg_2378 = data_V_dout.read().range(1029, 1020);
        data_tmp_1_33_V_reg_2383 = data_V_dout.read().range(1039, 1030);
        data_tmp_1_34_V_reg_2388 = data_V_dout.read().range(1049, 1040);
        data_tmp_1_35_V_reg_2393 = data_V_dout.read().range(1059, 1050);
        data_tmp_1_36_V_reg_2398 = data_V_dout.read().range(1069, 1060);
        data_tmp_1_37_V_reg_2403 = data_V_dout.read().range(1079, 1070);
        data_tmp_1_38_V_reg_2408 = data_V_dout.read().range(1089, 1080);
        data_tmp_1_39_V_reg_2413 = data_V_dout.read().range(1099, 1090);
        data_tmp_1_42_V_reg_2418 = data_V_dout.read().range(1129, 1120);
        data_tmp_1_43_V_reg_2423 = data_V_dout.read().range(1139, 1130);
        data_tmp_1_44_V_reg_2428 = data_V_dout.read().range(1149, 1140);
        data_tmp_1_46_V_reg_2433 = data_V_dout.read().range(1169, 1160);
        data_tmp_1_47_V_reg_2438 = data_V_dout.read().range(1179, 1170);
        data_tmp_1_48_V_reg_2443 = data_V_dout.read().range(1189, 1180);
        data_tmp_1_49_V_reg_2448 = data_V_dout.read().range(1199, 1190);
        data_tmp_1_4_V_reg_2268 = data_V_dout.read().range(749, 740);
        data_tmp_1_50_V_reg_2453 = data_V_dout.read().range(1209, 1200);
        data_tmp_1_51_V_reg_2458 = data_V_dout.read().range(1219, 1210);
        data_tmp_1_52_V_reg_2463 = data_V_dout.read().range(1229, 1220);
        data_tmp_1_53_V_reg_2468 = data_V_dout.read().range(1239, 1230);
        data_tmp_1_56_V_reg_2473 = data_V_dout.read().range(1269, 1260);
        data_tmp_1_57_V_reg_2478 = data_V_dout.read().range(1279, 1270);
        data_tmp_1_58_V_reg_2483 = data_V_dout.read().range(1289, 1280);
        data_tmp_1_5_V_reg_2273 = data_V_dout.read().range(759, 750);
        data_tmp_1_60_V_reg_2488 = data_V_dout.read().range(1309, 1300);
        data_tmp_1_61_V_reg_2493 = data_V_dout.read().range(1319, 1310);
        data_tmp_1_62_V_reg_2498 = data_V_dout.read().range(1329, 1320);
        data_tmp_1_63_V_reg_2503 = data_V_dout.read().range(1339, 1330);
        data_tmp_1_64_V_reg_2508 = data_V_dout.read().range(1349, 1340);
        data_tmp_1_65_V_reg_2513 = data_V_dout.read().range(1359, 1350);
        data_tmp_1_66_V_reg_2518 = data_V_dout.read().range(1369, 1360);
        data_tmp_1_67_V_reg_2523 = data_V_dout.read().range(1379, 1370);
        data_tmp_1_6_V_reg_2278 = data_V_dout.read().range(769, 760);
        data_tmp_1_7_V_reg_2283 = data_V_dout.read().range(779, 770);
        data_tmp_1_8_V_reg_2288 = data_V_dout.read().range(789, 780);
        data_tmp_1_9_V_reg_2293 = data_V_dout.read().range(799, 790);
    }
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, data_V_empty_n.read()));
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_0() {
    ap_return_0 = call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_0.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_1() {
    ap_return_1 = call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_1.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_10() {
    ap_return_10 = call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_10.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_11() {
    ap_return_11 = call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_11.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_12() {
    ap_return_12 = call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_12.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_13() {
    ap_return_13 = call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_13.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_14() {
    ap_return_14 = call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_14.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_15() {
    ap_return_15 = call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_0.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_16() {
    ap_return_16 = call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_1.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_17() {
    ap_return_17 = call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_2.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_18() {
    ap_return_18 = call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_3.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_19() {
    ap_return_19 = call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_4.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_2() {
    ap_return_2 = call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_2.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_20() {
    ap_return_20 = call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_5.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_21() {
    ap_return_21 = call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_6.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_22() {
    ap_return_22 = call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_7.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_23() {
    ap_return_23 = call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_8.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_24() {
    ap_return_24 = call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_9.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_25() {
    ap_return_25 = call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_10.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_26() {
    ap_return_26 = call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_11.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_27() {
    ap_return_27 = call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_12.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_28() {
    ap_return_28 = call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_13.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_29() {
    ap_return_29 = call_ret_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_525_ap_return_14.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_3() {
    ap_return_3 = call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_3.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_4() {
    ap_return_4 = call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_4.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_5() {
    ap_return_5 = call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_5.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_6() {
    ap_return_6 = call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_6.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_7() {
    ap_return_7 = call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_7.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_8() {
    ap_return_8 = call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_8.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_return_9() {
    ap_return_9 = call_ret2_i_pointwise_conv_1d_latency_cl_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_466_ap_return_9.read();
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_data_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_V_blk_n = data_V_empty_n.read();
    } else {
        data_V_blk_n = ap_const_logic_1;
    }
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_data_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, data_V_empty_n.read())))) {
        data_V_read = ap_const_logic_1;
    } else {
        data_V_read = ap_const_logic_0;
    }
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_data_tmp_0_0_V_fu_584_p1() {
    data_tmp_0_0_V_fu_584_p1 = data_V_dout.read().range(10-1, 0);
}

void pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config15_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, data_V_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

